version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=weather-api
      - MYSQL_USER=nest
      - MYSQL_PASSWORD=nest
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
